### ISSUE TITLE
Crear ManejadorDeArchivosYMetadatos

### ISSUE THREAD

**Issue by pciruzzi** [toblich/UDrive#10]
Crear una clase ManejadorDeArchivosYMetadatos que, por lo pronto, pueda crear carpetas y los archivos en el filesystem.
Deberá crear una carpeta por cada usuario y controlar el versionado de archivos (Hay que ver cual es la mejor forma de hacerlo).

**Comment by toblich** [comment]
### Metadatos

Como key de la DB de metadatos estará  
(Al menos por ahora, suponer que se recibe directo el JSON con los metadatos ya serializados).
- Al dar de alta un archivo, crear sus metadatos
- Actualizar metadatos (pisarlos con nuevos metadatos)
- Actualizar metadatos al darle permisos a otro (ver qué es necesario para esto)

#### A futuro:
- Búsquedas por permisos (no en el enunciado, pero hay que buscar ahí también lo demás), extensión, nombre, propietario y etiquetas. 
- Agregar el tema del versionado

**Comment by pciruzzi** [comment]
Para la búsqueda en archivos en los cuales tengo permisos, la idea sería tener en la base de datos de metadatos una key que sea "~permisos/<username>" y el value de la BD podría ser un JSON que contenga como key el nombre del archivo y como value del mismo el path (que deberia iniciar con el nombre del usuario que me compartio el archivo).

**Comment by sfernandez11** [comment]
Terminado, falta Versionado, Busquedas, Etiquetas, Permisos.
