### ISSUE TITLE
Conexion servidor cliente

### ISSUE THREAD

**Issue by plandino** [toblich/UDrive#16]
Hay que empezar a establecer la conexion entre el servidor y el cliente.
Que el cliente haga un GET con la direccion de una carpeta y el servidor devuelva un Json con la estructura de las carpetas y archivos adentro de esa carpeta.
Ademas el cliente tiene que poder hacer un PUT con un usuario y contraseña nuevos y el servidor tiene que guardar esa informacion.

**Comment by sfernandez11** [comment]
Terminado en el ultimo merge para el 1er checkpoint
