### ISSUE TITLE
JSON: Crear (des)serializador

### ISSUE THREAD

**Issue by toblich** [toblich/UDrive#3]
Crear Parser de JSON para serializar (meta)datos y para interpretar los json recibidos.
Debe tener las funcionalidades básicas como para definir en un futuro la estructura y los distintos tipos de dichos (meta)datos.

**Comment by pciruzzi** [comment]
Terminado y mergeada la branch feature/parserJson en commit 27d03d0da3e8e380fdb4273e829847c915266865
