### ISSUE TITLE
Agregar la parte de permisos al ManejadorArchivosYMetadatos

### ISSUE THREAD

**Issue by pciruzzi** [toblich/UDrive#32]
La idea sería tener en la base de datos de metadatos una key que sea "#permisos/<username>" y el value de la BD podría ser un string que contenga todos los archivos en los cuales tiene permisos. Este value de la BD podría ser, para un usuario 'pablo', algo así como 'pancho/datos/pepe.jpg#tobi/hola/asd.txt#santi/chau.txt', lo cual se deberá parsear y ver si esta o no.

**Comment by toblich** [comment]
Los archivos en la papelera tienen por nombre todo su path (interno desde la carpeta del usuario) reemplazando las `/` por `#`. Esto permite restaurarlos en su ubicación original e incluso tener varios archivos en la papelera con mismo nombre de archivo pero distinta ubicación original. 

> Ver cómo resolver el caso en que dos archivos se llaman igual y tienen misma ubicación (si el segundo en borrarse fue creado después de borrado el primero).

#### Pasos a seguir
- Modularizar/Refactorizar (especialmente el eliminar).
- Testear bien los permisos (lo mismo que se hace en los tests con el propietario, que lo haga otro con permisos).

**Comment by pciruzzi** [comment]
##### Para que no quede perdido:
- Al eliminar, además de lo ya mencionado en el comentario por Tobi, se agregó un número de secuencia para solucionar el tema de eliminar un archivo con el mismo nombre.
