### ISSUE TITLE
Búsquedas en Metadata

### ISSUE THREAD

**Issue by sfernandez11** [toblich/UDrive#36]
Tal como dice el enunciado hay que empezar a pensar como va a ser la logica para buscar archivos a partir de los metadatos. 
Las busquedas pueden ser por:
.Etiquetas
.Extension
.Nombre
.Propietario

**Comment by sfernandez11** [comment]
Segui con lo de las busquedas, como lo de "?" en el query_string no funciona como queria segun lo que me dijo pancho cambie la logica. Voy a esperar un parametro que sea busqueda=tipoDeBusqueda(etiquetas, extension,nombre,propietario) y otro parametro con tipoDeBusqueda=valor para usar ese "valor" para la busqueda.

Faltaria hacer lo de la busqueda por etiquetas que hay que ver como obtener esa lista para luego iterar e ir buscando una por una.
Tambien ver si la logica esta bien y los ifs feos eso que deje en el get de matadata.cpp

**Comment by pciruzzi** [comment]
Según lo que estuvimos haciendo hoy, sólo se puede buscar por una etiqueta. Habría que ver si es necesario/se pide hacer búsquedas por varias etiquetas. En ese caso, sería un and o un or de esas etiquetas? Es para charlar...

**Comment by sfernandez11** [comment]
En principio estaria terminado, falta probar todos los tipos de busqueda a ver si funcionan.
