### ISSUE TITLE
Continuar funcionalidades de ManjeadorArchivosYMetadatos (ver detalle...)

### ISSUE THREAD

**Issue by toblich** [toblich/UDrive#39]
#### Agregar:
- Cambiar nombre de archivo existente (no en la papelera)
- Eliminado definitivo de archivo en papelera
- En obtenerEstructura:
  - Caso especial de carpeta "compartidos conmigo" (no es una carpeta física).
  - Enviar el pathInterno en lugar del nombre del metadato.
- Eliminado de permisos (excluir a alguien que se le compartió el archivo)
  
  > Por ahora, se está eliminando en la lista de usuarios habilitados que tiene el archivo, pero no de la lista de archivos compartidos que tiene el usuario al que se le compartió.
#### Quedan pendientes:
- Búsquedas por metadatos
- Control de versiones

**Comment by pciruzzi** [comment]
#### Algunas cosas para mencionar:
- <b>ObtenerEstructura: </b>
  - Cual era el problema de mandar metadato.nombre en vez de pathInterno? Creo que venia dado porque despues no se podia saber cual era cual en el cliente y si llegaba a hacer alguna accion con ese archivo, anda a saber qué onda.
  - Capaz habria que cambiar la estructura de la base de datos de `^permisos/<username>` a `<username>/^permisos`, de manera de que quede consistente al pegarle a una uri para obtener la estructura quede como si fuera una carpeta mas del usuario.
- <b>Cambiar nombre de archivo:</b> Se podria llegar a hacer como que al actualizar los metadatos se fije si el nombre es el mismo que el path recibido. Si no es el mismo, es que cambio el nombre. Esto implica que en el FS y en la DB (Tanto en el metadato -value- como en el path -key-) tiene que tener siempre el mismo nombre.

##### De lo que puso Tobi quedaría:
- Cambiar nombre
- Mandar pathInterno en obtenerEstructura o archivoCompartido en obtenerEstructuraCompartidos (Que es una boludez, pero ver si es necesario y si con eso se soluciona el problema).
- <i><b>Agrego:</i></b> Terminar de ver el tema de la cuota con Santi (Que me la pase por parámetro).

Después de esto ya se podría arrancar el tema de las búsquedas.
