### ISSUE TITLE
Crear cliente Android básico

### ISSUE THREAD

**Issue by toblich** [toblich/UDrive#4]
Que tenga:
ventana de inicio (simbolo cargando o logo de la app)
ventana inicio de sesión
ventana crear cuenta

**Comment by plandino** [comment]
Ya cree las ventanas de Inicio (simbolo cargando con logo de la app), Inicio de sesion y de crear cuenta.
Hay una ventana principal basica que muestra las carpetas y se puede expandir un menu de opciones.
Continuo con realizar el manejo y vista de las carpetas y archivos.

**Comment by sfernandez11** [comment]
Terminado el básico, el cliente actual está en otro repositorio
