### ISSUE TITLE
Partir ManejadorArchivosYMetadatos en clases más pequeñas

### ISSUE THREAD

**Issue by toblich** [toblich/UDrive#43]
Dejar un ManejadorArchivosYMetadatos que sea un Facade que ordene el acceso a las siguientes clases más específicas:
- Manejador de Archivos (y carpetas)
- Manejador de Metadatos
- Buscador (por metadatos)
- Validador (el que ya está, quizás partido en validadores más específicos)

**Comment by toblich** [comment]
Ver commit 5cca1c03971ed490b83ba53b5de075be85c2f6f6

**Comment by pciruzzi** [comment]
El tema del eliminar es el siguiente:
- Existen 4 métodos que llevan a cabo la eliminacion dentro de ManejadorArchivosYMetadatos: eliminar, eliminarArchivo, eliminarCarpeta y mandarArchivoATrash.
- Con el eliminar carpeta en principio no habría problema, porque no toca la DB. El tema es que éste llama al eliminar. Al ver el método eliminar, para ver si se puede bajar al manejadorArchivos (Dejando el metodo del manejadorArchivosYMetadatos solo como un "pasamanos"), vemos que llama al eliminarArchivo, el cual debería bajarse al ManejadorArchivos. Aca es donde se complica, porque el eliminarArchivo, más allá de las validaciones, hace también la eliminacion de los metadatos, con lo que utiliza el manejadorMetadatos y ahí ya hay quilombo. A todo esto se le suma que también llama al mandarArchivoATrash (otro metodo del manejadorArchivosYMetadatos que podría ir al manejadorArchivos), que tambien hace baja en la DB, por lo que en caso de bajar uno, habría que bajar si o si los 4, lo cual a simple vista resulta inviable. Lo que voy a hacer por ahora es sacar algunas cosas de esos métodos que se puedan bajar al manejadorArchivos y listo.
