### ISSUE TITLE
Agregar Control de versiones

### ISSUE THREAD

**Issue by toblich** [toblich/UDrive#44]
En el ManejadorArchivosYMetadatos (y clases del subsistema cuando esté partido), agregar la lógica del control de versiones.
- Al renombrar un archivo, deberían renombrarse todas las versiones del mismo.

**Comment by pciruzzi** [comment]
A tener en cuenta:
- En la BD va a haber un unico metadato, que debería incluir el último número de versión.
- Se va a manejar con un número de secuencia indicando la versión del archivo.
- El cliente deberá guardar el número de versión que descargó, para luego hacer una comparación de versiones a la hora de subir/descargar.
- Al mandar una estructura de carpeta, el key no deberá contener el número de versión, pero sí deberá tenerlo el value (El último).
- A la hora de descargar, por default se descargará la última versión, aunque habrá una opción que permita descargar versiones anteriores.
- Los números de versiones arrancan desde 1.

**Comment by toblich** [comment]
Revisar:
- Orden de números de secuencia en trash: ahora viene primero la secuencia en trash y luego la versión. ¿Queda así o se invierte?
- Al borrar definitivamente un archivo de trash, se usa un wildcard de bash luego del `RESERVED_CHAR` (cuando el `ManejadorArchivosYMetadatos` llama al `ManejadorArchivos.eliminarArchivoDefinitivamente`). ¿No puede traer problemas en trash, donde hay doble número de secuencia (secuencia en trash y versión).

**Comment by toblich** [comment]
@PCiruzzi, acá resumo lo que hice  

### Estado actual:
- **Pasan todos los tests unitarios**, o sea que los archivos se suben, bajan, eliminan, actualizan, renombran (...etc) bien cuando se prueba **con una sola versión**. 
- **Están rotos muchos de los tests de integración**.

### Falta:
- Asegurarse de que siempre se cargue bien la version en los metadatos (al subir/actualizar archivos), o sea, que no llegue nunca con basura.
- Modificar el `Server` y los `RealizadoresDeEventos` para que manejen las versiones como corresponde.
- Modificar los tests de python de forma acorde.
- Testear realmente el versionado con varias versiones, que seguro falta cambiar cositas en quién sabe dónde...

#### Revisar:
- Orden de números de secuencia en trash: ahora viene primero la secuencia en trash y luego la versión. A mí me parece bien que quede así: el nombre unívoco (nombre + secuencia) seguida de la versión de ese archivo especial. Al revés también podría ser (creo que habíamos dicho de hacerlo al revés en realidad), pero cambiarlo sería una tremendísima paja.
- Al borrar definitivamente un archivo de trash, se usa un wildcard de bash luego del `RESERVED_CHAR` (cuando el `ManejadorArchivosYMetadatos` llama al `ManejadorArchivos.eliminarArchivoDefinitivamente`). ¿No puede traer problemas en trash, donde hay doble número de secuencia? (secuencia en trash y versión)?

**Comment by pciruzzi** [comment]
## Respecto a los comentarios de Tobi:
- Según probé, el wildcard de bash no trae problemas, ya que elimina bien todas las versiones de ese archivo (Pensar que en el filepath que se le pasa a `ManejadorArchivos.eliminarArchivoDefinitivamente` ya incluye el numero de secuencia en trash, por lo que elimina todos los que tengan ese numero de secuencia en trash). ~~Ahora, hay otro problema a resolver: imaginar que se elimina un archivo que tenia una sola version, luego se sube otro archivo con ese nombre y 2 versiones. La primer version no hay drama, pero la segunda quedará como que es la 0 en trash y la version 2, lo cual es incorrecto~~. (Ver últimos tests que prueban que funciona bien).
- El orden de los números de secuencia en trash queda bien porque permite la utilización del wildcard (En mi opinión queda mejor al revés, pero así se simplifican algunas cosas, asique queda así).
- Los metadatos de los tests ahora son todos correctos.
- Está testeado lo de varias versiones y salvo una modificación pequeña que tuve que hacer, funcionaba todo bien creo. Después se pueden llegar a agregar más tests, pero lo básico funciona creo.

### Falta:
- Modificar el `Server` y los `RealizadoresDeEventos` para que manejen las versiones como corresponde.
- Modificar los tests de python de forma acorde.
- Tests de descargas (No deberían ser gran cosa) con versionado.
- Tests de obtención de estructuras de carpetas y búsquedas con versionado (Si es que no sirven los que ya se habían hecho en su momento).
