### ISSUE TITLE
Documentar el código con Doxygen

### ISSUE THREAD

**Issue by pciruzzi** [toblich/UDrive#49]
Se debe empezar a documentar la utilización de los métodos de cada clase en los .h correspondientes.

**Comment by pciruzzi** [comment]
Para instalar Doxygen, simplemente hacer `sudo apt-get install doxygen`, habiendo instalado previamente con apt-get `libc6` y `libstdc++6`. Además, se pueden, mediante el mismo comando, agregar algunas dependencias como `doxygen-latex`, `doxygen-doc`, `doxygen-gui` y `graphviz` (Ver http://packages.ubuntu.com/precise/doxygen).

Ver también algunos tips de buenas prácticas de Doxygen en http://stackoverflow.com/questions/51667/best-tips-for-documenting-code-using-doxygen

**Comment by sfernandez11** [comment]
Hecho la documentación de la API REST, Server y Logger en el commit  956fb26 , me equivoque de número de issue
